### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by User123432123212** [dl4s-team/dl4s-evolution#6]
I am a student and for the past few days I have not been able to open my Safe Exam Browser without it telling me I need to configure something, I do not understand the steps and I can't do anything.

**Comment by philipturner** [comment]
I think you're asking the wrong people, but I'm willing to help you out. Could you please give me more details about your situation? What exactly is it saying you need to configure? How about screenshots? You could contact me over email (philipturner.AR@gmail.com) if you don't want to make that information public over a GitHub comment.

**Comment by philipturner** [comment]
Contact me over email for further discussion, as your problem is not directly related to DL4S.
